[my]
    anthropic_api_key      = "op://z3z72mlgus2ni7cd6hje3vifny/cvgfrbyilaryl5mdcrvhuz3bqa/credential"
    firecrawl_api_key      = "op://z3z72mlgus2ni7cd6hje3vifny/5v6vj27ik2ffqi2fejefavqtrq/credential"
    gemini_api_key         = "op://z3z72mlgus2ni7cd6hje3vifny/5v6vj27ik2ffqi2fejefavqtrq/credential"
    git_email              = "op://z3z72mlgus2ni7cd6hje3vifny/35fubhfnogjmju2pwu77j3u64q/email"
    git_signingkey         = "op://z3z72mlgus2ni7cd6hje3vifny/35fubhfnogjmju2pwu77j3u64q/signingkey"
    perplexity_api_key     = "op://z3z72mlgus2ni7cd6hje3vifny/koeddk2hanjbkx557pjnjrfaey/credential"
    requesty_api_key       = "op://z3z72mlgus2ni7cd6hje3vifny/33u7bny6wronxirqud5pwcyj5u/credential"
    twenty_one_dev_api_key = "op://z3z72mlgus2ni7cd6hje3vifny/l3ggqn4kz3q7zqgocp4ugtoxka/credential"

[work]
    airtable_api_key  = "op://53quluhq3elj2ryeb6itiilns4/pwhpnmiwxc3vm6imfngdt545qi/credential"
    wiz_client_id     = "op://53quluhq3elj2ryeb6itiilns4/no3gerdeydz6hcvjkncap7itey/username"
    wiz_client_secret = "op://53quluhq3elj2ryeb6itiilns4/no3gerdeydz6hcvjkncap7itey/credential"
