[my]
    anthropic_api_key      = "op://Dev/cvgfrbyilaryl5mdcrvhuz3bqa/credential"
    atlas_mcp_password     = "op://Dev/edlc6vc7tpkj7myig76ucfk7me/password"
    atlas_mcp_user         = "op://Dev/edlc6vc7tpkj7myig76ucfk7me/username"
    firecrawl_api_key      = "op://Dev/5v6vj27ik2ffqi2fejefavqtrq/credential"
    gemini_api_key         = "op://Dev/fgwtsgxzm676p3houcwf724tei/credential"
    git_email              = "op://Dev/35fubhfnogjmju2pwu77j3u64q/email"
    git_signingkey         = "op://Dev/35fubhfnogjmju2pwu77j3u64q/signingkey"
    openrouter_api_key     = "op://Dev/t7kzqyf3my2abnoovuti2zvwue/credential"
    perplexity_api_key     = "op://Dev/koeddk2hanjbkx557pjnjrfaey/credential"
    requesty_api_key       = "op://Dev/33u7bny6wronxirqud5pwcyj5u/credential"
    twenty_one_dev_api_key = "op://Dev/l3ggqn4kz3q7zqgocp4ugtoxka/credential"
    windsurf_api_key       = "op://Dev/ndeuwji34mcd5uysq6xh5fcupq/credential"

[work]
    airtable_api_key  = "op://Employee/pwhpnmiwxc3vm6imfngdt545qi/credential"
    wiz_client_id     = "op://Employee/no3gerdeydz6hcvjkncap7itey/username"
    wiz_client_secret = "op://Employee/no3gerdeydz6hcvjkncap7itey/credential"
