[secrets]
    21-dev-api-key     = "op://z3z72mlgus2ni7cd6hje3vifny/l3ggqn4kz3q7zqgocp4ugtoxka/credential"
    firecrawl_api_key  = "op://z3z72mlgus2ni7cd6hje3vifny/5v6vj27ik2ffqi2fejefavqtrq/credential"
    git_email          = "op://z3z72mlgus2ni7cd6hje3vifny/35fubhfnogjmju2pwu77j3u64q/email"
    git_signingkey     = "op://z3z72mlgus2ni7cd6hje3vifny/35fubhfnogjmju2pwu77j3u64q/signingkey"
    perplexity_api_key = "op://z3z72mlgus2ni7cd6hje3vifny/koeddk2hanjbkx557pjnjrfaey/credential"
